version: 2

updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /graphql
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /multiplayer
    schedule:
      interval: daily
