name: pokernook
region: nyc

databases:
  - cluster_name: db-redis-nyc1
    engine: REDIS
    name: db-redis-nyc1
    production: true
    version: "6"

  - cluster_name: db-postgresql-nyc1
    db_name: defaultdb
    db_user: doadmin
    engine: PG
    name: db-postgresql-nyc1
    production: true
    version: "12"

services:
  - name: graphql
    environment_slug: node-js
    github:
      repo: pokernook/pokernook
      branch: main
      deploy_on_push: true
    routes:
      - path: /api/graphql
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    build_command: |-
      npm run generate:prisma --workspace=graphql
      npm run generate:nexus --workspace=graphql
      npm run build --workspace=graphql
    run_command: |-
      npm exec --workspace=graphql -- prisma migrate deploy
      NODE_ENV=production npm start --workspace=graphql
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db-postgresql-nyc1.DATABASE_URL}
      - key: SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:eiPbITXerGgff5oFcdaIhvMI6WlYkqbi:Yw50HtTXwr0WS3GHlqaZzHQlUGmmIOkryXTGENyDmnl7o+Xk8GW/0H5U3Fa53MeG]
      - key: REDIS_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db-redis-nyc1.REDIS_URL}

  - name: web
    environment_slug: node-js
    github:
      repo: pokernook/pokernook
      branch: main
      deploy_on_push: true
    routes:
      - path: /
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    build_command: npm run build --workspace=web
    run_command: npm start --workspace=web
